#!/bin/bash -ex

rm /etc/init/cloud-*

dpkg-reconfigure openssh-server
sed "s/^.*PasswordAuthentication.*$/PasswordAuthentication yes/g" -i /etc/ssh/sshd_config 

adduser ubuntu
adduser ubuntu sudo

sed -i "s/^.*net.ipv4.ip_forward.*//g" /etc/sysctl.conf
echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
